# Nixpacks override to force Node.js detection
[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm install"]

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'LogLineOS Consciousness Build Complete'"]

[start]
cmd = "node bin/logline_gateway.js"